[versions]
androidxComposeBom = "2025.11.01"
androidGradlePlugin = "8.13.1"
androidxNavigation = "2.9.6"
androidxTestCore = "1.7.0"
coil = "2.7.0"
dependencyGuard = "0.5.0"
junit4 = "4.13.2"
kotlinxCoroutines = "1.10.2"
koin = "4.1.1"
kotlin = "2.2.21"
kover ="0.9.3"
ksp = "2.3.3"
ktor = "3.3.2"
mockk = "1.14.6"
room = "2.8.4"

[libraries]
activity-compose = { module = "androidx.activity:activity-compose" }
androidx-test-core = { module = "androidx.test:core", version.ref = "androidxTestCore" }
coil-compose = { module = "io.coil-kt:coil-compose", version.ref = "coil" }
coil-test = { module = "io.coil-kt:coil-test", version.ref = "coil" }
compose-bom = { module = "androidx.compose:compose-bom", version.ref = "androidxComposeBom" }
compose-material3 = { module = "androidx.compose.material3:material3" }
compose-material-iconsExtended = { group = "androidx.compose.material", name = "material-icons-extended" }
compose-ui = { module = "androidx.compose.ui:ui" }
compose-ui-test-junit4 = { module = "androidx.compose.ui:ui-test-junit4" }
compose-ui-test-manifest = { module = "androidx.compose.ui:ui-test-manifest" }
compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview" }
junit4 = { module = "junit:junit", version.ref = "junit4" }
koin-android = { module = "io.insert-koin:koin-android", version.ref = "koin" }
koin-android-test = { module = "io.insert-koin:koin-android-test", version.ref = "koin" }
koin-compose = { module = "io.insert-koin:koin-androidx-compose", version.ref = "koin" }
koin-test = { module = "io.insert-koin:koin-test", version.ref = "koin" }
koin-test-junit4 = { module = "io.insert-koin:koin-test-junit4", version.ref = "koin" }
ktor-client-android = { module = "io.ktor:ktor-client-android", version.ref = "ktor" }
ktor-client-content-negotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-client-mock = { module = "io.ktor:ktor-client-mock", version.ref = "ktor" }
ktor-serialization-kotlinx-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinxCoroutines" }
lifecycle-runtime-compose = { module = "androidx.lifecycle:lifecycle-runtime-compose" }
lifecycle-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose" }
mockk = { module = "io.mockk:mockk", version.ref = "mockk" }
mockk-android = { module = "io.mockk:mockk-android", version.ref = "mockk" }
navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "androidxNavigation" }
navigation-testing = { module = "androidx.navigation:navigation-testing", version.ref = "androidxNavigation" }
room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
room-ktx = { module = "androidx.room:room-ktx", version.ref = "room" }
room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
room-testing = { module = "androidx.room:room-testing", version.ref = "room" }

[bundles]
koin-android = ["koin-android", "koin-compose", "koin-android-test"]
koin-test = ["koin-test", "koin-test-junit4"]
ktor-client = [
    "ktor-client-core",
    "ktor-client-android",
    "ktor-client-content-negotiation",
    "ktor-serialization-kotlinx-json",
    "ktor-client-mock"
]

[plugins]
android-application = { id = "com.android.application", version.ref = "androidGradlePlugin" }
android-lint = { id = "com.android.lint", version.ref = "androidGradlePlugin" }
compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
dependency-guard = { id = "com.dropbox.dependency-guard", version.ref = "dependencyGuard" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
kover = { id = "org.jetbrains.kotlinx.kover", version.ref = "kover" }
